name: cmake

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cpp"
      - "**.ixx"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        v: [17]

    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja for C++ modules
      run: sudo apt-get install ninja-build

    - run: cmake --workflow --preset default
      env:
        CC: clang-${{ matrix.v }}
        CXX: clang++-${{ matrix.v }}
